all: Parametry.class Podzielnik.class Program.class

Parametry.class: Parametry.java
	javac Parametry.java

Podzielnik.class: Podzielnik.java
	javac Podzielnik.java

Program.class: Program.java
	javac Program.java

clean:
	rm *.class