all: parametry.class podzielnik.class program.class

parametry.class: parametry.java
	javac parametry.java

podzielnik.class: podzielnik.java
	javac podzielnik.java

program.class: program.java
	javac program.java
